import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(UI)/components/Footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import Navbar from "./(UI)/components/Navbar";
import UserProvider from "@/context/userProvider";
import NavbarRes from "./(UI)/components/NavbarRes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Futuretech Blog's",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-pcrollf scroll-smooth"
    >
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />

          <div className="flex justify-between flex-col h-[100vh]">
            <div>
              {/* <Navbar></Navbar> */}
              <NavbarRes></NavbarRes>
              <div className="mt-16 ">{children}</div>
            </div>
            <div className="b-0 bg-blue-300 text-center">
              <Footer></Footer>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
