import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(UI)/components/Footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import Navbar from "./(UI)/components/Navbar";
import UserProvider from "@/context/userProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Exploring NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <UserProvider >
     <ToastContainer />

<div className="flex justify-between flex-col h-[100vh]">
<div>
<Navbar></Navbar>

 {children}
</div>
 <div className="b-0 bg-blue-300 text-center">
 <Footer></Footer>
 </div>
</div>
 
     </UserProvider>

      
      </body>
    </html>
  );
}
